# Generated by Django 6.0.7 on 2026-08-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان پروژه را وارد کنید.', max_length=100, verbose_name='عنوان پروژه')),
                ('short_description', models.TextField(help_text='توضیح کوتاه برای نمایش در صفحه اصلی', max_length=250, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(max_length=2000, verbose_name='توضیحات اصلی پروژه')),
                ('cover_desktop', models.ImageField(help_text='نسبت تصویر 675 * 1200 پیکسل (16:9) و با ده درصد حاشیه امن باشد.', upload_to='projects/covers/desktop/', verbose_name='تصویر کاور دسکتاپ')),
                ('cover_mobile', models.ImageField(help_text='نسبت تصویر باید 900 * 600 (2:3) و با ده درصد حاشیه امن باشد.', upload_to='projects/covers/mobile/', verbose_name='تصویر کاور موبایل')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='لینک سایت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان تصویر')),
                ('desktop_image', models.ImageField(help_text='نسبت تصویر باید 900 * 1440 پیکسل و با ده درصد حاشیه امن باشد.', upload_to='projects/gallery/desktop/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(help_text='نسبت تصویر باید 844 * 390 و با ده درصد حاشیه امن باشد.', upload_to='projects/gallery/mobile/', verbose_name='تصویر موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
                'ordering': ['created_at'],
            },
        ),
    ]
