# Generated by Django 6.0.7 on 2026-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر، زودتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش'),
        ),
    ]
