# Generated by Django 6.0.7 on 2026-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='optometry-clinic', max_length=150, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
