# Generated by Django 6.0.7 on 2026-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
