# Generated by Django 6.0.7 on 2026-08-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عناون نمایشی در پنل ادمین')),
                ('description', models.TextField(help_text='متن درباره من رو اینجا بنویسید.', max_length=2000, verbose_name='متن توضیحات')),
            ],
            options={
                'verbose_name': ('درباره من',),
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دسته مهارت را وارد کنید.', max_length=100, unique=True, verbose_name='دسته مهارت')),
            ],
            options={
                'verbose_name': ('دسته بندی مهارت',),
                'verbose_name_plural': 'دسته بندی مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان مهارت را وارد کنید.', max_length=200, verbose_name='عنوان مهارت')),
                ('skill_image', models.ImageField(help_text='تصویر مهارت را وارد کنید. حداقل ابعاد 80 * 80 پیکسل (1:1)', upload_to='core/skills/icons/', verbose_name='تصویر مهارت')),
                ('displayStatus', models.BooleanField(default=True, help_text='در صورت غیر فعال بودن، نمایش داده نمی شود.', verbose_name='وضعیت نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='core.skillcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': ('مهارت',),
                'verbose_name_plural': 'مهارت ها',
            },
        ),
    ]
