# Generated by Django 6.0.7 on 2026-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر زودتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر زودتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش'),
        ),
    ]
