# Generated by Django 6.0.7 on 2026-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_display_order_skillcategory_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='توضیحات')),
                ('github_link', models.URLField(verbose_name='لینک GitHub')),
                ('linkedin_link', models.URLField(verbose_name='لینک LinkedIn')),
                ('instagram_link', models.URLField(blank=True, verbose_name='لینک Instagram')),
                ('telegram_link', models.URLField(blank=True, verbose_name='لینک Telegram')),
                ('iranian_social_link', models.URLField(blank=True, help_text='در صورت تمایل لینک یک شبکه اجتماعی ایرانی را وارد کنید.', verbose_name='لینک شبکه اجتماعی داخلی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
    ]
