# Generated by Django 6.0.7 on 2026-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_footer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح کوتاهی درباره این دسته از مهارت\u200cها وارد کنید.', max_length=300, verbose_name='توضیحات دسته'),
        ),
    ]
