# Generated by Django 6.0.7 on 2026-08-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skillcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='core.skillcategory', verbose_name='دسته بندی'),
        ),
    ]
