# Generated by Django 6.0.7 on 2026-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(help_text='تصویر مهارت را وارد کنید. حداقل ابعاد 80 * 80 پیکسل (1:1)', upload_to='core&contact_page/skills/icons/', verbose_name='تصویر مهارت'),
        ),
    ]
