# Generated by Django 5.1.15 on 2026-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_about_id_alter_footer_id_alter_skill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'آماده پذیرش پروژه'), ('busy', 'مشغول انجام پروژه'), ('unavailable', 'فعلاً در دسترس نیستم')], default='available', max_length=20, verbose_name='وضعیت')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='پیام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'وضعیت کاری',
                'verbose_name_plural': 'وضعیت کاری',
            },
        ),
    ]
