# Generated by Django 6.0.7 on 2026-08-11 15:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('short_intro', models.TextField(max_length=500, verbose_name='معرفی کوتاه')),
                ('profile_image', models.ImageField(help_text='ابعاد تصویر باید 1500 * 1200 پیکسل (نسبت 4:5) و با ده درصد حاشیه امن باشد.', upload_to='core&contact_page/about/', verbose_name='تصویر')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوای اصلی')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='لینک تلگرام')),
                ('iranian_social_link', models.URLField(blank=True, help_text='در صورت تمایل لینک یک شبکه اجتماعی ایرانی را وارد کنید.', verbose_name='لینک شبکه اجتماعی داخلی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
        ),
    ]
