# Generated by Django 6.0.7 on 2026-08-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': ('درباره من',), 'verbose_name_plural': 'درباره من'},
        ),
    ]
