# Generated by Django 6.0.7 on 2026-08-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': ('صفحه درباره من',), 'verbose_name_plural': 'صفحه درباره من'},
        ),
    ]
