# Generated by Django 5.1.15 on 2026-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutpage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='profile_image',
            field=models.ImageField(help_text='ابعاد تصویر باید 1500 * 1200 پیکسل (نسبت 4:5) و با ده درصد حاشیه امن باشد.', upload_to='core/about/', verbose_name='تصویر'),
        ),
    ]
